### ISSUE TITLE
Measurement URIs namespace in SHACL profile don't match measurement.owl URIs

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/HipHop#3]
In some cases, the SHACL profile uses "http://measurement.bibliotek-o.org/" (e.g. http://measurement.bibliotek-o.org/hasMeasurementGroup) whereas measurement.owl uses http://measurement.biblioteko-o.org/ (there's an extra o after bibliotek and before -o).
I'm not sure which way we want this, so am creating an issue.  I can do a pull request based on whichever namespace we wish to use.  Thanks!

**Comment by rjyounes** [comment]
It's bibliotek-o.org

**Comment by hudajkhan** [comment]
I'm assuming this means measurement.owl should be updated then.

**Comment by sfolsom** [comment]
Fixed in all the repos :)

**Comment by sfolsom** [comment]
Copied the typo from the original file, but all related file are cleaned up.
